sudo: required
branches:
  only:
    - master
    - next
    - /201[7-9][0-1][0-9][0-3][0-9]/
    - /^greenkeeper/.*$/

services: docker
install: true

language: C

script:
  - npm run test
  - ./travis-build.sh
